--CASE STATEMENT
UPDATE students
SET gender = CASE 
WHEN gender = 'M' THEN 'F'
WHEN gender = 'F' THEN 'M'
ELSE NULL
END 

--CASE EXPRESSION
select cust_name, case OPENING_AMT
WHEN  5000 THEN 'PRIME CUSTOMER'
WHEN  7000 THEN 'PLUS CUSTOMER'
ELSE 'REGULAR CUSTOMER'
END AS CUSTOMER_STATUS
FROM CUSTOMER
